/* generated by pull.js */
import _js from "./userscript.js";
import _css from "./style.css?raw";
import _asset from "./decrement.svg?url";
import _asset2 from "./increment.svg?url";
import _asset3 from "./settings.svg?url";
import _asset4 from "./toggle.svg?url";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "decrement.svg": _asset,
  "increment.svg": _asset2,
  "settings.svg": _asset3,
  "toggle.svg": _asset4,
};
