/* generated by pull.js */
import _js from "./userscript.js";
import _css from "./style.css?raw";
import _asset from "./lock.svg?url";
import _asset2 from "./unlock.svg?url";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "lock.svg": _asset,
  "unlock.svg": _asset2,
};
