/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Advanced Find & Replace",
  "description": "Enhanced find and replace functionality with global search across all sprites, regular expressions, batch operations, and advanced filtering. Includes search in comments, custom blocks, and cross-sprite dependency analysis.",
  "credits": [
    {
      "name": "Mistium",
      "url": "https://mistium.com"
    }
  ],
  "dynamicDisable": true,
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "settings": [
    {
      "dynamic": true,
      "name": "Enable regular expressions",
      "id": "enableRegex",
      "type": "boolean",
      "default": false
    },
    {
      "dynamic": true,
      "name": "Case sensitive search by default",
      "id": "caseSensitive",
      "type": "boolean",
      "default": false
    },
    {
      "dynamic": true,
      "name": "Search in comments",
      "id": "searchComments",
      "type": "boolean",
      "default": true
    },
    {
      "dynamic": true,
      "name": "Show search across all sprites",
      "id": "globalSearch",
      "type": "boolean",
      "default": true
    },
    {
      "dynamic": true,
      "name": "Maximum search results",
      "id": "maxResults",
      "type": "integer",
      "min": 10,
      "max": 1000,
      "default": 100
    }
  ],
  "tags": [
    "recommended",
    "editor"
  ],
  "enabledByDefault": false
};
export default manifest;
