/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Dev Inspector",
  "description": "Adds a right-click option to inspect blocks and view their JSON representation with useful debugging information.",
  "credits": [
    {
      "name": "Sophie"
    }
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "tags": [
    "developer"
  ],
  "enabledByDefault": true
};
export default manifest;
