/* generated by pull.js */
import _js from './userscript.js';
import _css from './style.css?raw';
import _css2 from './gamepadlib.css?raw';
import _asset from './active.png?url';
import _asset2 from './close.svg?url';
import _asset3 from './cursor.png?url';
import _asset4 from './dot.svg?url';
import _asset5 from './gamepad.svg?raw';
export const resources = {
    'userscript.js': _js,
    'style.css': _css,
    'gamepadlib.css': _css2,
    'active.png': _asset,
    'close.svg': _asset2,
    'cursor.png': _asset3,
    'dot.svg': _asset4,
    'gamepad.svg': _asset5
};
