/* generated by pull.js */
import _js from "./userscript.js";
import _css from "./hideOverflow.css?inline";
import _css2 from "./removeBorder.css?inline";
import _css3 from "./resizeWindow.css?inline";
import _css4 from "./resizeWindow_noToolbar.css?inline";
import _css5 from "./hideToolbar.css?inline";
export const resources = {
  "userscript.js": _js,
  "hideOverflow.css": _css,
  "removeBorder.css": _css2,
  "resizeWindow.css": _css3,
  "resizeWindow_noToolbar.css": _css4,
  "hideToolbar.css": _css5,
};
