/* generated by pull.js */
import _js from "./userscript.js";
import _css from "./userstyle.css?raw";
import _asset from "./collapse.svg?url";
import _asset2 from "./info.svg?url";
export const resources = {
  "userscript.js": _js,
  "userstyle.css": _css,
  "collapse.svg": _asset,
  "info.svg": _asset2,
};
