const name = 'None (Text Only)';

const guiColors = {};

const blockColors = {};

const icons = {
    Blocks: null,
    Costumes: null,
    Sounds: null,
    Extension: null,
    Check: null,
    X: null,
    Trash: null,
    Plus: null,
    CirclePlus: null,
    Edit: null,
    Download: null,
    Upload: null,
    Folder: null,
    FolderOpen: null,
    FolderInput: null,
    Settings: null,
    Settings2: null,
    Cog: null,
    Palette: null,
    Share: null,
    Share2: null,
    Search: null,
    Filter: null,
    ChevronDown: null,
    ChevronUp: null,
    ChevronLeft: null,
    ChevronRight: null,
    ArrowLeft: null,
    ArrowRight: null,
    Play: null,
    Pause: null,
    Minimize: null,
    Maximize: null,
    Maximize2: null,
    Eye: null,
    EyeOff: null,
    Copy: null,
    Globe: null,
    AlertTriangle: null,
    TriangleAlert: null,
    Info: null,
    InfoCircle: null,
    CheckCircle: null,
    XCircle: null,
    History: null,
    RotateCcw: null,
    DownloadSimple: null,
    UploadSimple: null,
    ExternalLink: null,
    Globe2: null,
    Book: null,
    BookType: null,
    Computer: null,
    Monitor: null,
    Sparkles: null,
    Paintbrush: null,
    Hand: null,
    CheckCheck: null,
    Search: null,
    Keyboard: null,
    HelpCircle: null,
    User: null,
    Crown: null,
    UserMinus: null,
    PenLine: null,
    FilePen: null,
    Zap: null,
    Binoculars: null,
    Trash2: null,
    Delete: null,
    ChevronDouble: null,
    ChevronsUpDown: null,
    ChevronsLeftRight: null,
    Menu: null,
    More: null,
    MoreVertical: null,
    RefreshCw: null,
    Save: null,
    Undo: null,
    Redo: null,
    Scissors: null,
    Move: null,
    PlusCircle: null,
    MinusCircle: null,
    ZoomIn: null,
    ZoomOut: null,
    Grid: null,
    List: null,
    Layers: null,
    Image: null,
    Code: null,
    Terminal: null,
    Database: null,
    Layout: null,
    AlignLeft: null,
    AlignCenter: null,
    AlignRight: null,
    Bold: null,
    Italic: null,
    Underline: null,
    Strikethrough: null,
    Link: null,
    Unlink: null,
    Quote: null,
    Heading: null,
    ListOrdered: null,
    ListTodo: null,
    CheckSquare: null,
    Square: null,
    Star: null,
    StarHalf: null,
    StarOff: null,
    Heart: null,
    HeartOff: null
};

export {
    name as displayName,
    name,
    icons,
    guiColors,
    blockColors
};
